polling_stations/apps/dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = "dashboard"

urlpatterns = [
    url(r"^$", views.IndexView.as_view(), name="index"),
    url(
        r"council/(?P<pk>[^/]+)/$",
        views.CouncilDetailView.as_view(),
        name="council_detail",
    ),
    url(
        r"council/(?P<council_pk>[^/]+)/polling-station/(?P<id>.+)/$",
        views.PollingStationDetailView.as_view(),
        name="pollingstation_detail",
    ),
    url(
        r"postcode/(?P<postcode>[^/]+)/$", views.PostCodeView.as_view(), name="postcode"
    ),
    url(
        r"postcode/(?P<postcode>[^/]+).geojson$",
        views.PostCodeGeoJSONView.as_view(),
        name="postcode-geojson",
    ),
]

polling_stations/urls.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from dc_theme.urls import dc_server_error

from api.router import router
from api.docs import ApiDocsView
from data_finder.views import (
    HomeView,
    PostcodeView,
    ExamplePostcodeView,
    AddressView,
    AddressFormView,
    WeDontKnowView,
    MultipleCouncilsView,
)
from pollingstations.views import status_check


admin.autodiscover()


core_patterns = [
    url(r"^status_check/$", status_check, name="status_check"),
    url(r"^postcode/(?P<postcode>.+)/$", PostcodeView.as_view(), name="postcode_view"),
    url(r"^postcode/$", PostcodeView.as_view(), name="postcode_view_alias"),
    url(r"^address/(?P<address_slug>.+)/$", AddressView.as_view(), name="address_view"),
    url(
        r"^we_dont_know/(?P<postcode>.+)/$",
        WeDontKnowView.as_view(),
        name="we_dont_know",
    ),
    url(
        r"^multiple_councils/(?P<postcode>.+)/$",
        MultipleCouncilsView.as_view(),
        name="multiple_councils_view",
    ),
    url(
        r"^address_select/(?P<postcode>.+)/$",
        AddressFormView.as_view(),
        name="address_select_view",
    ),
    url(r"^$", HomeView.as_view(), name="home"),
    url(
        r"^privacy/$",
        RedirectView.as_view(
            url="https://democracyclub.org.uk/privacy/", permanent=True
        ),
        name="privacy_view",
    ),
    url(
        r"^robots\.txt$",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
]

extra_patterns = [
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^api/beta/", include(router.urls)),
    url(r"^api/$", ApiDocsView.as_view(), name="api_docs"),
    url(r"^admin/", admin.site.urls),
    url(r"^report_problem/", include("bug_reports.urls")),
    url(r"^uploads/", include("file_uploads.urls", namespace="file_uploads")),
    url(r"^league_table/", include("data_collection.urls")),
    url(r"^example/$", ExamplePostcodeView.as_view(), name="example"),
    url(r"^email/", include("dc_signup_form.urls", namespace="dc_signup_form")),
    url(
        r"^about/$",
        RedirectView.as_view(
            url="https://democracyclub.org.uk/projects/polling-stations/",
            permanent=True,
        ),
        name="about",
    ),
]

if "dashboard" in settings.INSTALLED_APPS:
    extra_patterns.append(
        url(r"^dashboard/", include("dashboard.urls", namespace="dashboard"))
    )

PREFIXED_URLS = settings.EMBED_PREFIXES + settings.WHITELABEL_PREFIXES
for EMBED in PREFIXED_URLS:
    extra_patterns += [url(r"^%s/" % EMBED, include("whitelabel.urls"))]

urlpatterns = (
    extra_patterns
    + core_patterns
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

handler500 = dc_server_error

polling_stations/apps/dashboard/views.py
import json
import operator
import requests
from functools import reduce

from django.db import connection
from django.db.models import Q
from django.http import JsonResponse
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView, DetailView, ListView

from addressbase.models import Address
from councils.models import Council
from data_finder.helpers import RoutingHelper
from pollingstations.models import ResidentialAddress, PollingStation
from uk_geo_utils.models import Onspd
from uk_geo_utils.helpers import Postcode


class IndexView(ListView):
    queryset = Council.objects.select_related("dataquality")
    template_name = "dashboard/council_list.html"


class CouncilDetailView(DetailView):
    queryset = Council.objects.all()
    template_name = "dashboard/council_detail.html"

    def get_context_data(self, object, **kwargs):
        context = super().get_context_data(object=object, **kwargs)

        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT postcode, st_maxdistance(multipoint, multipoint)::int AS maxdistance
                FROM (
                    SELECT postcode, st_transform(st_collect(location), 27700) AS multipoint
                    FROM pollingstations_residentialaddress
                    WHERE council_id = %s
                    GROUP BY postcode
                ) AS subquery
                WHERE multipoint IS NOT NULL
                ORDER BY maxdistance DESC
                LIMIT 20;
            """,
                (object.pk,),
            )
            context["postcodes_by_diameter"] = cursor.fetchall()

        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    ps.internal_council_id,
                    ra.uprn,
                    ra.address,
                    ra.slug,
                    ra.postcode,
                    st_distance(
                        st_transform(ps.location, 27700),
                        st_transform(COALESCE(ra.location, onspd.location), 27700)
                    )::int AS distance
                FROM pollingstations_pollingstation ps,
                    pollingstations_residentialaddress ra
                LEFT OUTER JOIN uk_geo_utils_onspd onspd ON
                    onspd.pcds=LEFT(ra.postcode, LENGTH(ra.postcode)-3) || ' ' || RIGHT(ra.postcode, 3)
                WHERE ps.council_id=ra.council_id
                    AND ra.polling_station_id=ps.internal_council_id
                    AND ra.council_id=%s
                    AND ps.location IS NOT NULL
                    AND COALESCE(ra.location, onspd.location) IS NOT NULL
                ORDER BY distance DESC, ra.uprn, ra.slug
                LIMIT 100;
            """,
                (object.pk,),
            )
            context["distances_to_stations"] = cursor.fetchall()

        context["pollingstation_list"] = PollingStation.objects.filter(council=object)

        return context


class PostCodeView(TemplateView):
    template_name = "dashboard/postcode.html"

    def get_context_data(self, postcode, **kwargs):
        residential_addresses = ResidentialAddress.objects.filter(postcode=postcode)
        addresses = dict(
            Address.objects.filter(
                uprn__in=residential_addresses.values_list("uprn", flat=True)
            ).values_list("uprn", "address")
        )
        for residential_address in residential_addresses:
            residential_address.addressbase_address = addresses.get(
                residential_address.uprn
            )

        return {
            "postcode": postcode,
            "addresses": residential_addresses,
            "routing_helper": RoutingHelper(postcode),
        }


class PostCodeGeoJSONView(View):
    def get_approximate_postcode_boundary(self, postcode, **kwargs):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT ST_AsGeoJSON(pcds.*)
                FROM voronoi_pcds_mview as pcds
                WHERE pcds.pcd = %s;
                """,
                (postcode,),
            )
            return cursor.fetchall()

    station_colors = ["purple", "red", "blue", "yellow", "green", "pink", "orange"]

    def get(self, request, postcode):
        residential_addresses = ResidentialAddress.objects.filter(postcode=postcode)
        onspd = Onspd.objects.get(pcds=Postcode(postcode).with_space)
        station_ids = sorted(
            set(residential_addresses.values_list("council_id", "polling_station_id"))
        )
        if station_ids:
            stations = PollingStation.objects.filter(
                reduce(
                    operator.or_,
                    (
                        Q(
                            council_id=council_id,
                            internal_council_id=internal_council_id,
                        )
                        for council_id, internal_council_id in station_ids
                    ),
                )
            )
        else:
            stations = PollingStation.objects.none()
        station_colors = dict(zip(station_ids, self.station_colors))
        return JsonResponse(
            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "geometry": json.loads(station.location.geojson)
                        if station.location
                        else None,
                        "properties": {
                            "type": "pollingstation",
                            "council_id": station.council_id,
                            "internal_council_id": station.internal_council_id,
                            "address": station.address,
                            "color": station_colors[
                                (station.council_id, station.internal_council_id)
                            ],
                            "url": reverse(
                                "dashboard:pollingstation_detail",
                                args=(station.council_id, station.internal_council_id),
                            ),
                        },
                    }
                    for station in stations
                ]
                + [
                    {
                        "type": "Feature",
                        "geometry": json.loads(residential_address.location.geojson)
                        if residential_address.location
                        else None,
                        "properties": {
                            "type": "residentialaddress",
                            "address": residential_address.address,
                            "color": station_colors[
                                (
                                    residential_address.council_id,
                                    residential_address.polling_station_id,
                                )
                            ],
                            "uprn": residential_address.uprn,
                            "url": reverse(
                                "address_view", args=(residential_address.slug,)
                            ),
                        },
                    }
                    for residential_address in residential_addresses
                ]
                + [
                    {
                        "type": "Feature",
                        "geometry": json.loads(onspd.location.geojson)
                        if onspd.location
                        else None,
                        "properties": {
                            "type": "onspd",
                            "address": onspd.pcd,
                            "color": "cyan",
                            "url": "",
                        },
                    }
                ]
                + [json.loads(self.get_approximate_postcode_boundary(postcode)[0][0]),],
            },
            content_type="application/geo+json",
        )


class PollingStationDetailView(DetailView):
    template_name = "dashboard/pollingstation_detail.html"
    queryset = PollingStation.objects.all()

    def get_object(self, queryset=None):
        return self.queryset.get(
            council_id=self.kwargs["council_pk"], internal_council_id=self.kwargs["id"]
        )

polling_stations/apps/dashboard/templates/dashboard/council_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}

{% block page_title %}{{ council }} - {% trans "Dashboard" %}{% endblock page_title %}

{% block content %}
    <h1>{{ council }}</h1>

    <section class="card">
        <h2>Report</h2>
        <pre>{{ council.dataquality.report }}</pre>
    </section>


    <section class="card">
        <h2>Postcodes by diameter</h2>
        <table>
            <thead>
            <tr>
                <th>Postcode</th>
                <th>Diameter (metres)</th>
            </tr>
            </thead>
            <tbody>{% for postcode, diameter in postcodes_by_diameter %}
                <tr>
                    <td><a href="{% url "dashboard:postcode" postcode=postcode %}">{{ postcode }}</a> (<a href="{% url "postcode_view" postcode %}">site</a>)</td>
                    <td>{{ diameter|intcomma }}</td>
                </tr>{% endfor %}

            </tbody>
        </table>
    </section>

    <section class="card">
        <h2>Largest distances to polling places</h2>
        <table>
            <thead>
            <tr>
                <th>UPRN</th>
                <th>Address</th>
                <th>Post code</th>
                <th>Polling station</th>
                <th>Distance (metres)</th>
            </tr>
            </thead>
            <tbody>{% for pollingstation_id, uprn, address, slug, postcode, distance in distances_to_stations %}
                <tr>
                    <td>{{ uprn }}</td>
                    <td>
                        <a href="{% url "address_view" slug %}">{{ address }}</a>
                    </td>
                    <td><a href="{% url "dashboard:postcode" postcode=postcode %}">{{ postcode }}</a> (<a href="{% url "postcode_view" postcode %}">site</a>)</td>
                    <td>{{ pollingstation_id }}</td>
                    <td>{{ distance|intcomma }}</td>
                </tr>{%  endfor %}
            </tbody>
        </table>
    </section>

    <section class="card">
        <h2>Polling places</h2>
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Address</th>
                <th>Postcode</th>
                <th>Location?</th>
            </tr>
            </thead>
            <tbody>{% for pollingstation in pollingstation_list %}
                <tr>
                    <td><a href="{% url "dashboard:pollingstation_detail" pollingstation.council_id pollingstation.internal_council_id %}">{{ pollingstation.internal_council_id }}</a></td>
                    <td>{{ pollingstation.address }}</td>
                    <td>{{ pollingstation.postcode }}</td>
                    <td>{{ pollingstation.location|yesno }}</td>
                </tr>{% endfor %}
            </tbody>
        </table>
    </section>
{% endblock content %}

polling_stations/apps/dashboard/templates/dashboard/council_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Dashboard" %}{% endblock page_title %}

{% block content %}
    <h1>Dashboard</h1>

    <section class="card">
        <table>
            <thead>
            <tr>
                <th>Council</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Stations</th>
                <th>Districts</th>
                <th>Addresses</th>
            </tr>
            </thead>
            <tbody>{% for council in council_list %}
                <tr>
                    <td>
                        <a href="{% url "dashboard:council_detail" pk=council.pk %}">{{ council }}</a>
                    </td>
                    <td>{% if council.email %}<a href="mailto:{{ council.email }}">{{ council.email }}</a>{% endif %}</td>
                    <td>{{ council.electoral_services_phone_numbers.0 }}</td>
                    <td>{{ council.dataquality.num_stations|default:"" }}</td>
                    <td>{{ council.dataquality.num_districts|default:"" }}</td>
                    <td>{{ council.dataquality.num_addresses|default:"" }}</td>
                </tr>{% endfor %}
            </tbody>
        </table>
    </section>
{% endblock content %}

polling_stations/apps/dashboard/templates/dashboard/pollingstation_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block page_title %}{{ pollingstation.address }}{% endblock page_title %}

{% block content %}
    <h1>{{ pollingstation.address }}</h1>

    <p><a href="{% url "dashboard:council_detail" pollingstation.council_id %}">{{ pollingstation.council }}</a></p>


{% endblock content %}

polling_stations/apps/dashboard/templates/dashboard/postcode.html
{% extends "base.html" %}
{% load i18n %}
{% load pipeline %}

{% block page_title %}{% trans "Postcode:" %} {{ postcode }}{% endblock page_title %}

{% block extra_page_css %}
    {% stylesheet 'map' %}
    {% stylesheet 'dashboard' %}
{% endblock extra_page_css %}

{% block extra_javascript %}
    {% javascript 'map' %}
    {% javascript 'dashboard' %}
{% endblock extra_javascript %}


{% block in_page_javascript %}
    <script type="text/javascript">
        (function() {

            var typeIcons = {
                'pollingstation': 'fa-check-square',
                'residentialaddress': 'fa-home',
                'onspd': 'fa-flag'
            };

            tiles = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: 'Map data ⓒ <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
                subdomains: 'abc'
            });

            map = L.map('area_map', {
                layers: [tiles]
            });

            fetch('{% url "dashboard:postcode-geojson" postcode %}').then((response) => {
                response.json().then((json) => {
                    layer = L.geoJSON(json, {
                        pointToLayer: (feature, latlng) => {
                            var popup = document.createElement("div");
                            popup.appendChild(document.createElement("p")).textContent = feature.properties.address;
                            if (feature.properties.uprn) {
                                popup.appendChild(document.createElement("p")).textContent = feature.properties.uprn;
                            }
                            var viewLink = popup.appendChild(document.createElement("a"));
                            viewLink.textContent = "View";
                            viewLink.setAttribute("href", feature.properties.url);
                            return L.marker(latlng, {icon: L.ExtraMarkers.icon({
                                    icon: typeIcons[feature.properties.type] || 'fa-question',
                                    markerColor: feature.properties.color,
                                    iconColor: 'white',
                                    shape: 'circle',
                                    prefix: 'fa'
                                })}).bindPopup(popup);
                        },
                    });
                    var clusteredMarkers = L.markerClusterGroup({maxClusterRadius: 1});
                    clusteredMarkers.addLayer(layer);
                    map.addLayer(clusteredMarkers);
                    map.fitBounds(layer.getBounds(), {padding: [30, 30]});
                })
            });

        })();
    </script>
{% endblock in_page_javascript %}


{% block content %}
    <h1>{{ postcode }}</h1>


    <div id="area_map" class="card">

    </div>

    <section class="card">
        <h2>User view</h2>

        <p><a href="{% url "postcode_view" postcode %}">View ({{ routing_helper.route_type }})</a></p>
    </section>

    <section class="card">
        <h2>Addresses</h2>

        <table>
            <thead>
            <tr>
                <th>Council address</th>
                <th>AddressBase address</th>
                <th>UPRN</th>
                <th>Polling place</th>
            </tr>
            </thead>
            <tbody>{% for address in addresses %}
                <tr>
                    <td>{{ address.address }}</td>
                    <td>{{ address.addressbase_address|default:"" }}</td>
                    <td>{{ address.uprn }}</td>
                    <td><a href="{% url "dashboard:pollingstation_detail" address.council_id address.polling_station_id %}">{{ address.polling_station_id }}</a></td>
                </tr>{% endfor %}
            </tbody>
        </table>
    </section>

{% endblock content %}