polling_stations/apps/file_uploads/urls.py
from django.conf.urls import url

from .views import CouncilListView, CouncilDetailView, FileDetailView, FileUploadView

app_name = "file_uploads"
urlpatterns = [
    url(r"^councils/$", CouncilListView.as_view(), name="councils_list"),
    url(
        r"^councils/(?P<pk>.+)/$",
        CouncilDetailView.as_view(),
        name="councils_detail",
    ),
    url(
        r"^files/(?P<pk>.+)/$",
        FileDetailView.as_view(),
        name="files_detail",
    ),
    url(
        r"^upload_files/(?P<gss>.+)/$",
        FileUploadView.as_view(),
        name="file_upload",
    ),
]

polling_stations/urls.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from dc_theme.urls import dc_server_error

from api.router import router
from api.docs import ApiDocsView
from data_finder.views import (
    HomeView,
    PostcodeView,
    ExamplePostcodeView,
    AddressView,
    AddressFormView,
    WeDontKnowView,
    MultipleCouncilsView,
)
from pollingstations.views import status_check


admin.autodiscover()


core_patterns = [
    url(r"^status_check/$", status_check, name="status_check"),
    url(r"^postcode/(?P<postcode>.+)/$", PostcodeView.as_view(), name="postcode_view"),
    url(r"^postcode/$", PostcodeView.as_view(), name="postcode_view_alias"),
    url(r"^address/(?P<address_slug>.+)/$", AddressView.as_view(), name="address_view"),
    url(
        r"^we_dont_know/(?P<postcode>.+)/$",
        WeDontKnowView.as_view(),
        name="we_dont_know",
    ),
    url(
        r"^multiple_councils/(?P<postcode>.+)/$",
        MultipleCouncilsView.as_view(),
        name="multiple_councils_view",
    ),
    url(
        r"^address_select/(?P<postcode>.+)/$",
        AddressFormView.as_view(),
        name="address_select_view",
    ),
    url(r"^$", HomeView.as_view(), name="home"),
    url(
        r"^privacy/$",
        RedirectView.as_view(
            url="https://democracyclub.org.uk/privacy/", permanent=True
        ),
        name="privacy_view",
    ),
    url(
        r"^robots\.txt$",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
]

extra_patterns = [
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^api/beta/", include(router.urls)),
    url(r"^api/$", ApiDocsView.as_view(), name="api_docs"),
    url(r"^admin/", admin.site.urls),
    url(r"^report_problem/", include("bug_reports.urls")),
    url(r"^uploads/", include("file_uploads.urls", namespace="file_uploads")),
    url(r"^league_table/", include("data_collection.urls")),
    url(r"^example/$", ExamplePostcodeView.as_view(), name="example"),
    url(r"^email/", include("dc_signup_form.urls", namespace="dc_signup_form")),
    url(
        r"^about/$",
        RedirectView.as_view(
            url="https://democracyclub.org.uk/projects/polling-stations/",
            permanent=True,
        ),
        name="about",
    ),
]

if "dashboard" in settings.INSTALLED_APPS:
    extra_patterns.append(
        url(r"^dashboard/", include("dashboard.urls", namespace="dashboard"))
    )

PREFIXED_URLS = settings.EMBED_PREFIXES + settings.WHITELABEL_PREFIXES
for EMBED in PREFIXED_URLS:
    extra_patterns += [url(r"^%s/" % EMBED, include("whitelabel.urls"))]

urlpatterns = (
    extra_patterns
    + core_patterns
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

handler500 = dc_server_error

polling_stations/apps/file_uploads/models.py
from django.contrib.gis.db import models

from councils.models import Council


status_map = {
    "Pending": "⌛",
    "Error": "❌",
    "OK": "✔️",
}


def status_to_emoji(status):
    if status in status_map:
        return status_map[status]
    return status


class Upload(models.Model):
    gss = models.ForeignKey(
        Council,
        null=True,
        db_constraint=False,
        on_delete=models.DO_NOTHING,
    )
    timestamp = models.DateTimeField()
    github_issue = models.CharField(blank=True, max_length=100)

    class Meta:
        get_latest_by = "timestamp"

    def __str__(self):
        return f"{self.timestamp}: {self.gss}"

    @property
    def status(self):
        if not self.file_set.all():
            return "Pending"
        for f in self.file_set.all():
            if not f.csv_valid:
                return "Error"
        return "OK"

    @property
    def status_emoji(self):
        return status_to_emoji(self.status)


class File(models.Model):
    upload = models.ForeignKey(Upload, on_delete=models.CASCADE)
    csv_valid = models.BooleanField()
    csv_rows = models.IntegerField(default=0)
    ems = models.CharField(max_length=40)
    key = models.CharField(max_length=255)
    errors = models.TextField(blank=True)

    def __str__(self):
        return self.key

    @property
    def filename(self):
        return self.key.split("/")[-1]

    @property
    def path(self):
        return "/".join(self.key.split("/")[:-1]) + "/"

    @property
    def status(self):
        if self.csv_valid:
            return "OK"
        return "Error"

    @property
    def status_emoji(self):
        return status_to_emoji(self.status)

polling_stations/apps/file_uploads/views.py
import json
import logging
from datetime import datetime

from django.conf import settings
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import ValidationError as DjangoValidationError
from django.db.models import Prefetch
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect, ensure_csrf_cookie
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, TemplateView

import boto3
from boto.pyami.config import Config
from botocore.exceptions import ClientError
from marshmallow import Schema, fields, validate
from marshmallow import ValidationError as MarshmallowValidationError

from councils.models import Council
from .models import File, Upload


class FileSchema(Schema):
    name = fields.String(
        required=True,
        validate=validate.Regexp(
            r"(?i)^.+(\.csv|\.tsv)$", error="Unexpected file type"
        ),
    )
    size = fields.Integer(
        required=True,
        validate=validate.Range(
            min=0, max=settings.MAX_FILE_SIZE, error="File too big"
        ),
    )
    type = fields.String(required=False)


class UploadRequestSchema(Schema):
    files = fields.List(
        fields.Nested(FileSchema()),
        required=True,
        validate=validate.Length(min=1, max=2),
    )


def get_s3_client():
    config = Config()
    access_key = config.get_value(settings.BOTO_SECTION, "aws_access_key_id")
    secret_key = config.get_value(settings.BOTO_SECTION, "aws_secret_access_key")
    return boto3.client(
        "s3", aws_access_key_id=access_key, aws_secret_access_key=secret_key
    )


class RequireStaffMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_active and self.request.user.is_staff


logger = logging.getLogger(__name__)


class FileUploadView(RequireStaffMixin, TemplateView):
    template_name = "file_uploads/upload.html"

    @method_decorator(ensure_csrf_cookie)
    def get(self, request, *args, **kwargs):
        return super().get(self, request, *args, **kwargs)

    def get_context_data(self, **context):
        context["council"] = (
            Council.objects.all()
            .exclude(council_id__startswith="N09")
            .defer("area")
            .get(council_id=self.kwargs["gss"])
        )
        return context

    def validate_body(self, body):
        """
        Do some basic picture checks on request body and files.
        Obviously these values can be spoofed, so checks on
        file extension and MIME type etc are just to "fail fast".
        We will check the files _properly_ in the lambda hook.
        """
        try:
            UploadRequestSchema().load(body)
        except MarshmallowValidationError as e:
            # for now, log the error and body to sentry
            # so we've got visibility on errors
            logger.error(f"{e}\n{body}")

            raise DjangoValidationError("Request body did not match schema")

        files = body["files"]
        if len(files) == 2 and files[0]["name"] == files[1]["name"]:
            raise DjangoValidationError("Files must have different names")

    @method_decorator(csrf_protect)
    def post(self, request, *args, **kwargs):
        body = json.loads(request.body)

        try:
            self.validate_body(body)
            try:
                council = Council.objects.get(pk=self.kwargs["gss"])
            except Council.DoesNotExist as e:
                raise DjangoValidationError(str(e))
        except DjangoValidationError as e:
            return JsonResponse({"error": e.message}, status=400)

        client = get_s3_client()
        now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S.%f")

        resp = {"files": []}
        for f in body["files"]:
            bucket_name = settings.S3_UPLOADS_BUCKET
            object_name = f"{self.kwargs['gss']}/{now}/{f['name']}"
            fields = {"Content-Type": f["type"]}
            conditions = [
                {"Content-Type": f["type"]},
                ["content-length-range", 0, settings.MAX_FILE_SIZE],
            ]
            expiration = 600  # 10 mins
            try:
                resp["files"].append(
                    client.generate_presigned_post(
                        bucket_name,
                        object_name,
                        Fields=fields,
                        Conditions=conditions,
                        ExpiresIn=expiration,
                    )
                )
                Upload.objects.get_or_create(gss=council, timestamp=now)
            except ClientError:
                return JsonResponse(
                    {"error": "Could not authorize request"}, status=400
                )
        return JsonResponse(resp, status=200)


class CouncilView:
    def get_queryset(self):
        uploads = Upload.objects.all().order_by("-timestamp")
        qs = (
            Council.objects.all()
            .exclude(council_id__startswith="N09")
            .defer("area")
            .order_by("name")
            .prefetch_related(Prefetch("upload_set", uploads))
            .prefetch_related("upload_set__file_set")
        )
        return qs


class CouncilListView(RequireStaffMixin, CouncilView, ListView):
    template_name = "file_uploads/council_list.html"


class CouncilDetailView(RequireStaffMixin, CouncilView, DetailView):
    template_name = "file_uploads/council_detail.html"


class FileDetailView(RequireStaffMixin, DetailView):
    template_name = "file_uploads/file_detail.html"
    model = File

polling_stations/apps/file_uploads/templates/file_uploads/council_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}

{% block page_title %}{{ object.name }} - {% trans "Uploads" %}{% endblock page_title %}

{% block content %}
  {% include "file_uploads/uploads_header.html" %}

  <section class="card">
    <h1>{{ object.name }} - Uploads</h1>

    <p>
      <a href="{% url 'file_uploads:file_upload' gss=object.council_id %}" class="link-button">
        Upload
      </a>
    </p>

    {% for upload in object.upload_set.all %}
        <h3>{{ upload.timestamp | naturaltime }}
        {% if upload.github_issue %} -
        <a href="{{ upload.github_issue }}">GitHub issue</a>
        {% endif %}
        </h3>

        {% if upload.file_set.all %}
          <ul style="list-style-type:none">
            {% for file in upload.file_set.all %}
            <li>
              {{ file.status_emoji }}
              {{ file.path }}
              <a href="{% url 'file_uploads:files_detail' pk=file.id %}">
                {{ file.filename }}
              </a>
            </li>
          {% endfor %}
          </ul>
        {% else %}
          Waiting...
        {% endif %}

    {% empty %}
      No uploads found!
    {% endfor %}
  </section>
{% endblock content %}

polling_stations/apps/file_uploads/templates/file_uploads/council_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Uploads" %}{% endblock page_title %}

{% block content %}
  {% include "file_uploads/uploads_header.html" %}

  <section class="card">
    <h1>Uploads</h1>

    <table>
      <thead>
        <tr>
          <th>Council ID</th>
          <th>Council Name</th>
          <th>Email</th>
          <th>Upload</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for council in object_list %}
          <tr>
            <td>{{ council.council_id }}</td>
            <td>
              <a href="{% url 'file_uploads:councils_detail' pk=council.council_id %}">
                {{ council.name }}
              </a>
            </td>
            <td><a href="mailto:{{ council.email }}">{{ council.email }}</a></td>
            <td>
              <a href="{% url 'file_uploads:file_upload' gss=council.council_id %}">
                upload
              </a>
            </td>
            <td>
              {{ council.upload_set.latest.status_emoji }}
            </td>
          </tr>
        {% empty %}
          <tr><td colspan="4">No councils found!</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
{% endblock content %}

polling_stations/apps/file_uploads/templates/file_uploads/file_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}{{ object.filename }}{% endblock page_title %}

{% block extra_page_css %}
<style>
  dt {
      float: left;
  }
  dt::after{
      content: ":";
  }
  dd {
      margin-left: 25%;
  }
  dd::after {
      content: " ";
      display: block;
      clear: left;
  }
</style>
{% endblock extra_page_css %}

{% block content %}
  {% include "file_uploads/uploads_header.html" %}

  <section class="card">
    <h1>{{ object.filename }}</h1>

    <dl>
      <dt><strong>Location</strong></dt>
      <dd><code>{{ object.key }}</code></dd>

      <dt><strong>EMS</strong></dt>
      <dd>{{ object.ems }}</dd>

      <dt><strong>Errors</strong></dt>
      <dd>
        {{ object.status_emoji }}
        {% if object.csv_valid %}OK{% else %}{{ object.errors | linebreaksbr }}{% endif %}
      </dd>
    </dl>

  </section>
{% endblock content %}

polling_stations/apps/file_uploads/templates/file_uploads/index.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_page_css %}
<style>
  button:disabled {
    background-color: lightgrey;
    border-color: darkgrey;
  }
</style>
{% endblock extra_page_css %}

{% block content %}

{% include "file_uploads/uploads_header.html" %}

<div class="card">

    <noscript>
      <div class="card error-summary">
          <h2>Javascript disabled</h2>
          <p>To upload files, please enable javascript.</p>
      </div>
    </noscript>

    <h2>Upload Files</h2>

    <form id="file_upload_form" method="POST">

        <div class="card error-summary" id="error" hidden></div>

        <p>
          <label for="council_id">Council</label>
          <select id="council_id" name="council_id">
            {% for council in councils %}
            <option value="{{ council.council_id }}">{{ council.name }}</option>
            {% endfor %}
          </select>
        </p>

        <p>
          <label for="file0">File 1 (required)</label>
          <input type="file" id="file0" name="file0" accept=".csv,.tsv" required />
          <progress id="progressBar0" value="0" max="100"></progress>
        </p>
        <p>
          <label for="file1">File 2 (optional)</label>
          <input type="file" id="file1" name="file1" accept=".csv,.tsv" />
          <progress id="progressBar1" value="0" max="100"></progress>
        </p>

        <div>
        <button type="submit" class="button" id="submit">Upload</button>

        </div>
      </form>

</div>
{% endblock content %}

{% block in_page_javascript %}
<script>
var getCookie = function(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      // Does this cookie string begin with the name we want?
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
};

var handleError = function(err) {
  var error = '<h2>Sorry, something has gone wrong</h2> '
  error += '<p>Ensure the file you are uploading is of type .csv or .tsv. ';
  error += 'If the problem continues, ';
  error += '<a href="mailto:pollingstations@democracyclub.org.uk">contact us</a>.</p>';
  document.getElementById("error").innerHTML = error;
  document.getElementById("error").hidden = false;
  document.getElementById("submit").disabled = false;
};

var serializeFile = function(file) {
  if (file == null) return null;
  return {
    name: file.name,
    size: file.size,
    type: file.type,
  };
};

var getPresignedPostData = function() {
  return new Promise(function(resolve, reject) {
    var xhr = new XMLHttpRequest();
    var url = '{% url "file_uploads:file_upload_index" %}';
    xhr.open("POST", url, true);
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    var payload = {
      files: [
        serializeFile(document.getElementById('file0').files[0]),
        serializeFile(document.getElementById('file1').files[0])
      ].filter(Boolean),
      council_id: document.getElementById('council_id').value
    };
    xhr.send(JSON.stringify(payload));
    xhr.onload = function() {
      if (this.status === 200) {
        resolve(JSON.parse(this.responseText));
       } else {
        reject(this.responseText);
       }
    };
  });
};

var uploadFileToS3 = function(presignedPostData, file, progressBar) {
  return new Promise(function(resolve, reject) {
    var formData = new FormData();
    Object.keys(presignedPostData.fields).forEach(function(key) {
      formData.append(key, presignedPostData.fields[key]);
    });

    formData.append("file", document.getElementById(file).files[0]);

    var xhr = new XMLHttpRequest();
    xhr.open("POST", presignedPostData.url, true);
    xhr.upload.addEventListener("progress", function(event) {
      document.getElementById(progressBar).value = (event.loaded / event.total) * 100;
    }, false);
    xhr.send(formData);
    xhr.onload = function() {
      if (this.status === 204) {
        resolve(this.responseText);
      } else {
        reject(this.responseText);
      }
    };
  });
};

document.addEventListener('DOMContentLoaded', function() {

  document.getElementById('file_upload_form').addEventListener("submit", function (e) {
    e.preventDefault();
    document.getElementById("error").innerHTML = "";
    document.getElementById("error").hidden = true;
    document.getElementById("submit").disabled = true;

    getPresignedPostData().then(
      function(data) {
        var uploads = [];
        for (var i=0; i<data.files.length; i++) {
          uploads.push(
            uploadFileToS3(data.files[i], 'file'.concat(i), 'progressBar'.concat(i))
          );
        }
        Promise.all(uploads).then(
          function(data) {
            console.log('done!');
            console.log(data);
            window.location.href = '{% url "file_uploads:councils_list" %}';
            document.getElementById("submit").disabled = false;
          },
          handleError
        );

      },
      handleError
    );

  });

});
</script>
{% endblock in_page_javascript %}

polling_stations/apps/file_uploads/templates/file_uploads/upload.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_page_css %}
<style>
  button:disabled {
    background-color: lightgrey;
    border-color: darkgrey;
  }
</style>
{% endblock extra_page_css %}

{% block content %}

{% include "file_uploads/uploads_header.html" %}

<div class="card">

    <noscript>
      <div class="card error-summary">
          <h2>Javascript disabled</h2>
          <p>To upload files, please enable javascript.</p>
      </div>
    </noscript>

    <h2>Upload Files: {{ council.name }}</h2>

    <form id="file_upload_form" method="POST">
        <div class="card error-summary" id="error" hidden></div>

        <p>
          <label for="file0">File 1 (required)</label>
          <input type="file" id="file0" name="file0" accept=".csv,.tsv" required />
          <progress id="progressBar0" value="0" max="100"></progress>
        </p>
        <p>
          <label for="file1">File 2 (optional)</label>
          <input type="file" id="file1" name="file1" accept=".csv,.tsv" />
          <progress id="progressBar1" value="0" max="100"></progress>
        </p>

        <div>
        <button type="submit" class="button" id="submit">Upload</button>
        </div>
      </form>

</div>
{% endblock content %}

{% block in_page_javascript %}
<script>
var getCookie = function(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      // Does this cookie string begin with the name we want?
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
};

var handleError = function(err) {
  var error = '<h2>Sorry, something has gone wrong</h2> '
  error += '<p>Ensure the file you are uploading is of type .csv or .tsv. ';
  error += 'If the problem continues, ';
  error += '<a href="mailto:pollingstations@democracyclub.org.uk">contact us</a>.</p>';
  document.getElementById("error").innerHTML = error;
  document.getElementById("error").hidden = false;
  document.getElementById("submit").disabled = false;
};

var serializeFile = function(file) {
  if (file == null) return null;
  return {
    name: file.name,
    size: file.size,
    type: file.type,
  };
};

var getPresignedPostData = function() {
  return new Promise(function(resolve, reject) {
    var xhr = new XMLHttpRequest();
    var url = '{% url "file_uploads:file_upload" gss=gss %}';
    xhr.open("POST", url, true);
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    var payload = {
      files: [
        serializeFile(document.getElementById('file0').files[0]),
        serializeFile(document.getElementById('file1').files[0])
      ].filter(Boolean),
    };
    xhr.send(JSON.stringify(payload));
    xhr.onload = function() {
      if (this.status === 200) {
        resolve(JSON.parse(this.responseText));
       } else {
        reject(this.responseText);
       }
    };
  });
};

var uploadFileToS3 = function(presignedPostData, file, progressBar) {
  return new Promise(function(resolve, reject) {
    var formData = new FormData();
    Object.keys(presignedPostData.fields).forEach(function(key) {
      formData.append(key, presignedPostData.fields[key]);
    });

    formData.append("file", document.getElementById(file).files[0]);

    var xhr = new XMLHttpRequest();
    xhr.open("POST", presignedPostData.url, true);
    xhr.upload.addEventListener("progress", function(event) {
      document.getElementById(progressBar).value = (event.loaded / event.total) * 100;
    }, false);
    xhr.send(formData);
    xhr.onload = function() {
      if (this.status === 204) {
        resolve(this.responseText);
      } else {
        reject(this.responseText);
      }
    };
  });
};

document.addEventListener('DOMContentLoaded', function() {

  document.getElementById('file_upload_form').addEventListener("submit", function (e) {
    e.preventDefault();
    document.getElementById("error").innerHTML = "";
    document.getElementById("error").hidden = true;
    document.getElementById("submit").disabled = true;

    getPresignedPostData().then(
      function(data) {
        var uploads = [];
        for (var i=0; i<data.files.length; i++) {
          uploads.push(
            uploadFileToS3(data.files[i], 'file'.concat(i), 'progressBar'.concat(i))
          );
        }
        Promise.all(uploads).then(
          function(data) {
            console.log('done!');
            console.log(data);
            window.location.href = '{% url "file_uploads:councils_detail" pk=gss %}';
            document.getElementById("submit").disabled = false;
          },
          handleError
        );

      },
      handleError
    );

  });

});
</script>
{% endblock in_page_javascript %}

polling_stations/apps/file_uploads/templates/file_uploads/uploads_header.html
<a href="{% url 'file_uploads:councils_list' %}">Home</a> •
<a href="{% url 'logout' %}">Logout</a>